### ISSUE TITLE
Select-erasing input text is not updating the form control value

### ISSUE THREAD

**Issue by mperez-TCA** [rbalet/ngx-mat-input-tel#4]
When you select the whole input text and erase it, the formControl value doesn't update and keeps the previously written value. Different than when you erase it character by character, in this case the form value does update.

It can be replicated in the stackblitz demo: https://stackblitz.com/~/github.com/rbalet/ngx-mat-input-tel
![NgxMatInputTel - Selected input text value](https://github.com/rbalet/ngx-mat-input-tel/assets/101586233/f94ace8e-7e83-443b-8aa3-dcd3eb2e5f80)
![NgxMatInputTel - Erased input text value wasn't updated in FormControl](https://github.com/rbalet/ngx-mat-input-tel/assets/101586233/a160cd44-a5b7-42a1-89a8-cd35bc7a5c51)

The issue can be worked around by disabling the input text selection events.

**Comment by mperez-TCA** [comment]
Btw, thank you a lot for your hard work, the component is really well done and useful, helped me a lot with a current project. ♥

**Comment by rbalet** [comment]
@mperez-TCA Good catch, should be fixed in the latest update: https://github.com/rbalet/ngx-mat-input-tel/releases/tag/v18.1.2

Closing the issue. 
Don't hesitate to open it again if this does not work.

Don't forget to [pay me a coffee](https://buymeacoffee.com/widness) if you find this library worthful 

Have a nice day
