### ISSUE TITLE
Is it posible to define max length and always return form control value?

### ISSUE THREAD

**Issue by mperez-TCA** [rbalet/ngx-mat-input-tel#5]
Hi, me again

I noticed that the form control value is only returned when there is a valid phone number entered, is it possible to always return the input value? I tried using a valueChanged event for the control, but the returned value is always null until it's a valid one.

![NgxMatInputTel - Only returning value when phone is valid](https://github.com/user-attachments/assets/4dac98cb-3244-410c-8e8d-1f5bde353930)

Also, I've found that after the entered value length is greater than 17 characters, it is no longer detected as an entered value and doesn't return the "validatePhoneNumber" control error. And if the country is changed in this state, the entered value is erased.

Video with demonstration:
https://github.com/user-attachments/assets/e8586186-e9c2-411e-b7d5-83c5a123ea74

If it could be possible to define a max param for the input, it would be great as well.

Thank you, have a good one!

**Comment by rbalet** [comment]
Hi @mperez-TCA and thx for the coffees ;).

I've 

1. Added the possibility to add `maxLength: string | number` and added `15` as his default value, as it seems to be the max world wide > available in the latest version https://github.com/rbalet/ngx-mat-input-tel/releases/tag/v18.2.0

2. You can add your own validators, then you'll see if you get any error directly by getting `[control].value.errors`. I've added you an example in the code example, [here](https://stackblitz.com/~/github.com/rbalet/ngx-mat-input-tel?file=projects/ngx-mat-input-tel-tester/src/app/app.component.ts:L46-L48)

3. I've seen that `enablePlaceholder: boolean` weren't working, so I fixed it.  
    I had to add some little css to make it looks cosy with two new variable, `--ngxMatInputTel-selector-opacity` and `--ngxMatInputTel-placeholder-opacity`. 
 
4. I'm not sure I understand why the former maintainer didn't wanted the input to always emit the phone number. (Maybe because of poor understanding of the Validator), but I've change it

Everything & more explained in the [v18.2.2](https://github.com/rbalet/ngx-mat-input-tel/releases/tag/v18.2.2)
